### ISSUE TITLE
YSF Functions 

### ISSUE THREAD

**Issue by P4lw4** [nexquery/samp-textdraw-streamer#6]
YSF Functions "Conflict"

I was attempting to use PlayerTextDrawSetPos while using both YSF and this plugin. But, it makes the function didn't work (because both have the same native for this?). For me, it's only work if i only use one of these plugins (either YSF or this plugin). While i have to use both of these plugins for my server at the same time.

I'm looking for a solution to make PlayerTextDrawSetPos working even if i use YSF and this plugin at the same time. Maybe you can just change all of the YSF Function natives's name in this plugin?

**Comment by nexquery** [comment]
Hello, I have this problem in the open.mp version. I will update the plugin soon, if you have any suggestions for the plugin you can tell.
